# Generated by Django 3.2.1 on 2021-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='arete',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='bloodpool',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='glory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='gnosis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='honor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='humanity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='quintessence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='rage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='virtue0',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='virtue1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='virtue2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='wisdom',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
