# Generated by Django 3.2.1 on 2021-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20210618_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='angst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='banality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='corpus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='darkpassion0',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='darkpassion1',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='darkpassion2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='darkpassion3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='darkpassion4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='dynamic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='entropic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='fetter0',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='fetter1',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='fetter2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='fetter3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='fetter4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='glamour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='legacies',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='paradox',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='passion0',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='passion1',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='passion2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='passion3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='passion4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='pathos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='psyche',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='creature',
            name='psyche_archetype',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='creature',
            name='psyche_willpower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='realm0',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='realm1',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='realm2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='realm3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='realm4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='regret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='static',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='thorn0',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='thorn1',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='thorn2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='thorn3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='thorn4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
