# Generated by Django 3.2.1 on 2021-06-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20210619_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='level0',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='power1',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='power2',
        ),
    ]
