# Generated by Django 3.2.1 on 2021-06-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20210619_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='gift0',
            new_name='trait0',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift1',
            new_name='trait1',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift10',
            new_name='trait10',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift11',
            new_name='trait11',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift12',
            new_name='trait12',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift13',
            new_name='trait13',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift14',
            new_name='trait14',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift15',
            new_name='trait15',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift2',
            new_name='trait2',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift3',
            new_name='trait3',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift4',
            new_name='trait4',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift5',
            new_name='trait5',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift6',
            new_name='trait6',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift7',
            new_name='trait7',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift8',
            new_name='trait8',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='gift9',
            new_name='trait9',
        ),
    ]
