# Generated by Django 3.2.1 on 2021-06-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20210620_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='display_gauge',
            field=models.IntegerField(default=0),
        ),
    ]
