# Generated by Django 3.2.1 on 2021-06-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20210620_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='new_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
