# Generated by Django 3.2.1 on 2021-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_creature_new_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
