# Generated by Django 3.2.1 on 2022-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_creature_background10'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
