# Generated by Django 3.2.12 on 2022-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_creature_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='notes_on_backgrounds',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='creature',
            name='notes_on_history',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='creature',
            name='notes_on_meritsflaws',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
