# Generated by Django 3.2.12 on 2022-05-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20220425_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('name', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('chronicle', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.chronicle')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='adventure',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.adventure'),
        ),
    ]
