# Generated by Django 3.2.12 on 2022-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20220502_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='notes_on_naturedemeanor',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='creature',
            name='notes_on_traits',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
