# Generated by Django 2.2.4 on 2023-05-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_creature_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='cast_figure',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
