# Generated by Django 2.2.4 on 2023-05-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_creature_cast_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='list_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
