# Generated by Django 2.2.4 on 2023-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_creature_list_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicle',
            name='era',
            field=models.IntegerField(default=2023),
        ),
    ]
