# Generated by Django 2.2.4 on 2023-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_auto_20230529_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='players_starting_freebies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
