# Generated by Django 2.2.4 on 2023-05-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_discipline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
