# Generated by Django 2.2.4 on 2023-05-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_delete_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('code', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('alternative_name', models.CharField(default='', max_length=128)),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('declaration', models.CharField(blank=True, default='', max_length=256)),
                ('clan_0', models.BooleanField(default=False, verbose_name='Brujah')),
                ('clan_1', models.BooleanField(default=False, verbose_name='Gangrel')),
                ('clan_2', models.BooleanField(default=False, verbose_name='Malkavian')),
                ('clan_3', models.BooleanField(default=False, verbose_name='Nosferatu')),
                ('clan_4', models.BooleanField(default=False, verbose_name='Toreador')),
                ('clan_5', models.BooleanField(default=False, verbose_name='Tremere')),
                ('clan_6', models.BooleanField(default=False, verbose_name='Ventrue')),
                ('clan_7', models.BooleanField(default=False, verbose_name='Lasombra')),
                ('clan_8', models.BooleanField(default=False, verbose_name='Tzimisce')),
                ('clan_9', models.BooleanField(default=False, verbose_name='Assamites')),
                ('clan_10', models.BooleanField(default=False, verbose_name='Giovanni')),
                ('clan_11', models.BooleanField(default=False, verbose_name='Ravnos')),
                ('clan_12', models.BooleanField(default=False, verbose_name='Setite')),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('technical_notes', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
