# Generated by Django 2.2.4 on 2023-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_auto_20230529_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='alternative_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(default='?', max_length=128, primary_key=True, serialize=False),
        ),
    ]
