# Generated by Django 2.2.4 on 2023-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_auto_20230529_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='has_rituals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='alternative_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
