# Generated by Django 2.2.4 on 2023-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_auto_20230529_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
