# Generated by Django 4.2.1 on 2023-06-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_alter_chronicle_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='is_storyteller_only',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
