# Generated by Django 4.2.1 on 2023-06-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0042_alter_background_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='cumulate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
