# Generated by Django 4.2.1 on 2023-07-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0044_adventure_protagonists_adventure_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
