# Generated by Django 4.2.1 on 2023-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0045_alter_adventure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
