# Generated by Django 4.2.1 on 2023-07-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0046_adventure_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
