# Generated by Django 4.2.1 on 2023-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0047_adventure_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='chronicle',
            field=models.CharField(default='NYC', max_length=8),
        ),
    ]
