# Generated by Django 5.0 on 2024-06-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0052_gift_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='declaration',
            new_name='code',
        ),
    ]
