# Generated by Django 5.0 on 2024-06-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0053_rename_declaration_gift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='pre_change_access',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribes',
            field=models.CharField(default='................', max_length=16),
        ),
    ]
