# Generated by Django 5.0 on 2024-06-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0054_creature_pre_change_access_alter_gift_tribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rite',
            old_name='declaration',
            new_name='code',
        ),
    ]
