# Generated by Django 5.0 on 2024-06-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0058_alter_creature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='chronicle',
            field=models.CharField(default='WOD', max_length=8),
        ),
    ]
