# Generated by Django 5.0 on 2024-06-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0059_alter_creature_chronicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sept',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('protagonists', models.CharField(blank=True, default='', max_length=1024)),
                ('notes', models.TextField(blank=True, default='', max_length=1024)),
                ('chronicle', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.chronicle')),
            ],
        ),
    ]
