# Generated by Django 5.0 on 2024-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0060_sept'),
    ]

    operations = [
        migrations.AddField(
            model_name='sept',
            name='rid',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sept',
            name='protagonists',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
