# Generated by Django 5.0 on 2024-06-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0063_alter_creature_adventure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sept',
            old_name='protagonists',
            new_name='garous',
        ),
        migrations.AddField(
            model_name='sept',
            name='kinfolks',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='creature',
            name='adventure',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
