# Generated by Django 5.0 on 2024-07-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0066_creature_reparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='community_job',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
