# Generated by Django 5.0 on 2024-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0067_creature_community_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='players_starting_freebies',
            field=models.IntegerField(blank=True, default=15),
        ),
    ]
