# Generated by Django 5.0 on 2024-07-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0070_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='code',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='code',
            new_name='acronym',
        ),
    ]
