# Generated by Django 5.0 on 2024-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0071_rename_code_adventure_acronym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='chronicle',
        ),
        migrations.AddField(
            model_name='adventure',
            name='season',
            field=models.CharField(default='DEF', max_length=8),
        ),
    ]
