# Generated by Django 5.0 on 2024-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0073_alter_adventure_protagonists_alter_adventure_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='protagonists',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
