# Generated by Django 5.0 on 2024-07-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0074_alter_adventure_protagonists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='players_starting_freebies',
        ),
    ]
