# Generated by Django 5.0 on 2024-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0075_remove_season_players_starting_freebies'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='era',
            field=models.PositiveIntegerField(blank=True, default=1985),
        ),
    ]
