# Generated by Django 5.0 on 2024-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0076_season_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='is_player',
            field=models.BooleanField(default=False),
        ),
    ]
