# Generated by Django 5.0 on 2024-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0078_sept_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='notes_on_history',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
