# Generated by Django 5.0 on 2024-07-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0081_alter_creature_notes_on_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='notes_on_others',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
