# Generated by Django 5.0 on 2024-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0082_creature_notes_on_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='sept',
            name='caller_of_the_wild',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='elders',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sept',
            name='gatekeeper',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='grand_elder',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='guardians',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sept',
            name='keeper_of_the_land',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='master_of_challenge',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='master_of_the_howl',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='master_of_the_rite',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='talesinger',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='truthcatcher',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='warder',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='wyrmfoe',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sept',
            name='garous',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='sept',
            name='kinfolks',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
