# Generated by Django 5.0 on 2024-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0083_sept_caller_of_the_wild_sept_elders_sept_gatekeeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='tribe_16',
            field=models.BooleanField(default=False, verbose_name='White Howlers'),
        ),
        migrations.AddField(
            model_name='sept',
            name='auspices',
            field=models.CharField(blank=True, default='0 0 0 0 0', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='breeds',
            field=models.CharField(blank=True, default='0 0 0', max_length=128),
        ),
        migrations.AddField(
            model_name='sept',
            name='tribes',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=128),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_10',
            field=models.BooleanField(default=False, verbose_name='Shadow Lords'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_11',
            field=models.BooleanField(default=False, verbose_name='Silent Striders'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_12',
            field=models.BooleanField(default=False, verbose_name='Silver Fangs'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_13',
            field=models.BooleanField(default=False, verbose_name='Stargazers'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_14',
            field=models.BooleanField(default=False, verbose_name='Uktenas'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tribe_15',
            field=models.BooleanField(default=False, verbose_name='Wendigos'),
        ),
    ]
