# Generated by Django 5.0 on 2024-07-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0085_alter_creature_pre_change_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sept',
            name='treemap',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
    ]
