# Generated by Django 5.0 on 2024-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0086_alter_sept_treemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='references',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
