# Generated by Django 5.0 on 2024-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0088_gift_pretty_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
