# Generated by Django 5.0 on 2024-08-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0091_creature_garou_rank_alter_creature_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='extra_freebies',
            field=models.IntegerField(default=0),
        ),
    ]
