# Generated by Django 5.0 on 2024-09-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0093_creature_background11_creature_background12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='background12',
        ),
    ]
