# Generated by Django 5.0 on 2024-09-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0095_adventure_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
