# Generated by Django 5.0 on 2024-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0096_season_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='challenge',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
