# Generated by Django 5.0 on 2024-11-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0097_creature_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='specialities_rationale',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
