# Generated by Django 5.0 on 2025-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0105_creature_freebies_exp_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='adventure_teaser',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
