# Generated by Django 5.1.12 on 2025-09-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0107_alter_creature_notes_on_meritsflaws_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='anthithesis',
            new_name='antithesis',
        ),
    ]
