# Generated by Django 5.0 on 2026-02-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0109_creature_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='current',
            new_name='is_current',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='current',
            new_name='is_current',
        ),
    ]
