# Generated by Django 5.0 on 2026-02-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0110_rename_current_adventure_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sept',
            name='treemap',
            field=models.TextField(blank=True, default='{}', max_length=16384),
        ),
    ]
