# Generated by Django 5.0 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0111_alter_sept_treemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sept',
            name='caern_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sept',
            name='caern_totem',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
