# Generated by Django 5.0 on 2026-02-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0113_adventure_chronicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='chronicle',
        ),
    ]
