# Generated by Django 5.0 on 2026-03-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0114_remove_season_chronicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='path',
            field=models.CharField(default='', max_length=128),
        ),
    ]
