# Generated by Django 5.0 on 2026-03-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0115_discipline_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='path',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
