# Generated by Django 5.0 on 2026-03-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0116_alter_discipline_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="ritual_pathes",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
