# Generated by Django 5.0 on 2026-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0118_deed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
