# Generated by Django 5.0 on 2026-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0123_creature_season_alter_creature_adventure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creature",
            name="season",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
