# Generated by Django 5.0 on 2026-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0124_alter_creature_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='sept',
            name='faction',
            field=models.CharField(blank=True, default='Gaia', max_length=32),
        ),
    ]
