# Generated by Django 5.0 on 2026-03-25 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0126_gift_source_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
