# Generated by Django 5.0 on 2026-03-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0127_gift_date_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="id",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
