# Generated by Django 5.0 on 2026-03-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0128_gift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='date_pub',
        ),
    ]
