# Generated by Django 5.0 on 2026-03-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0130_alter_gift_id_alter_gift_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="lower_name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
