# Generated by Django 5.0 on 2026-03-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0131_gift_lower_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='orphan',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
