# Generated by Django 5.0.14 on 2026-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_gift_orphan'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='new_acronym',
            field=models.CharField(default='', max_length=32),
        ),
    ]
