# Generated by Django 5.0.14 on 2026-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0133_adventure_new_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="refcode",
            field=models.IntegerField(default=0),
        ),
    ]
