# Generated by Django 5.0.14 on 2026-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_adventure_refcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='refcode',
            field=models.IntegerField(default=0),
        ),
    ]
