# Generated by Django 5.0.14 on 2026-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0135_season_refcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="chronicle",
            name="refcode",
            field=models.IntegerField(default=0),
        ),
    ]
