# Generated by Django 5.0.14 on 2026-04-05 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0136_chronicle_refcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creature",
            options={"ordering": ["name"], "verbose_name": "Creature"},
        ),
    ]
