# Generated by Django 5.0.14 on 2026-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0137_alter_creature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rite',
            name='page',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
