# Generated by Django 5.0.14 on 2026-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0140_alter_rite_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="rite",
            name="refcode",
            field=models.IntegerField(default=0),
        ),
    ]
