# Generated by Django 5.0.14 on 2026-04-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0142_alter_rite_name_alter_rite_refcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='refcode',
            field=models.IntegerField(default=0),
        ),
    ]
