# Generated by Django 5.0.14 on 2026-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0143_creature_refcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='acronym',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='refcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
