# Generated by Django 5.0.14 on 2026-04-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0145_alter_adventure_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='refcode',
            new_name='id',
        ),
    ]
