# Generated by Django 5.0.14 on 2026-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0146_rename_refcode_adventure_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sept",
            name="recode",
            field=models.IntegerField(default=0),
        ),
    ]
