# Generated by Django 5.0.14 on 2026-04-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0147_sept_recode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sept',
            old_name='recode',
            new_name='refcode',
        ),
    ]
