# Generated by Django 5.0.14 on 2026-04-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0149_alter_sept_name_alter_sept_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sept',
            old_name='refcode',
            new_name='id',
        ),
    ]
