# Generated by Django 5.0.14 on 2026-04-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0151_alter_season_name_alter_season_refcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="refcode",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
