# Generated by Django 5.0.14 on 2026-04-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0152_alter_season_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='refcode',
            new_name='id',
        ),
    ]
