# Generated by Django 5.0.14 on 2026-04-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0153_rename_refcode_season_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
