# Generated by Django 5.0.14 on 2026-04-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0154_alter_gift_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="refcode",
            field=models.IntegerField(default=0),
        ),
    ]
