# Generated by Django 5.0.14 on 2026-04-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0156_alter_discipline_code_alter_discipline_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='refcode',
            new_name='id',
        ),
    ]
