# Generated by Django 5.0.14 on 2026-04-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0157_rename_refcode_discipline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
