# Generated by Django 5.0.14 on 2026-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0158_alter_totem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rite',
            name='name',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rite',
            name='refcode',
            field=models.IntegerField(default=0),
        ),
    ]
