# Generated by Django 5.0.14 on 2026-04-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0159_alter_rite_name_alter_rite_refcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rite',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='rite',
            name='refcode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
