# Generated by Django 5.0.14 on 2026-04-06 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0160_alter_rite_name_alter_rite_refcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rite",
            old_name="refcode",
            new_name="id",
        ),
    ]
