# Generated by Django 5.0.14 on 2026-04-06 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0162_remove_creature_id_alter_creature_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='refcode',
            new_name='id',
        ),
    ]
