# Generated by Django 5.0.14 on 2026-04-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0163_rename_refcode_creature_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="background",
            name="refcode",
            field=models.IntegerField(default=0),
        ),
    ]
