# Generated by Django 5.0.14 on 2026-04-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0164_background_refcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='code',
            field=models.CharField(default='?', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='refcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
