# Generated by Django 5.0.14 on 2026-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0165_alter_background_code_alter_background_refcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="refcode",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
