# Generated by Django 5.0.14 on 2026-04-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0166_alter_background_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='refcode',
            new_name='id',
        ),
    ]
