# Generated by Django 5.0.14 on 2026-04-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0167_rename_refcode_background_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='refcode',
            field=models.IntegerField(default=0),
        ),
    ]
