# Generated by Django 5.0.14 on 2026-04-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0169_alter_archetype_name_alter_archetype_refcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='refcode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
