# Generated by Django 5.0.14 on 2026-04-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0170_alter_archetype_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archetype',
            old_name='refcode',
            new_name='id',
        ),
    ]
