# Generated by Django 5.0.14 on 2026-04-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0171_rename_refcode_archetype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deed",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
