# Generated by Django 5.0.14 on 2026-04-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0173_alter_adventure_new_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='players_starting_freebies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
