# Generated by Django 5.0.14 on 2026-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0174_alter_adventure_players_starting_freebies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicle',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='refcode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
