# Generated by Django 5.0.14 on 2026-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0176_alter_creature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sept',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
