# Generated by Django 6.0.4 on 2026-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0177_alter_sept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='jaggling_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
