# Generated by Django 6.0.4 on 2026-04-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0178_totem_jaggling_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='brood',
            field=models.CharField(default='', max_length=128),
        ),
    ]
