# Generated by Django 6.0.4 on 2026-04-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0179_totem_brood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='brood',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='totem',
            name='jaggling_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='totem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
