# Generated by Django 6.0.4 on 2026-04-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0180_alter_totem_brood_alter_totem_jaggling_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='granted_powers',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
