# Generated by Django 6.0.4 on 2026-04-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0181_totem_granted_powers'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='type',
            field=models.CharField(blank=True, choices=[('HON', 'Honor'), ('CUN', 'Cunning'), ('WAR', 'War'), ('WIS', 'Wisdom')], default='Honor', max_length=16),
        ),
    ]
