# Generated by Django 6.0.4 on 2026-04-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0182_totem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='type',
            field=models.CharField(blank=True, choices=[('HON', 'Honor'), ('CUN', 'Cunning'), ('WAR', 'War'), ('WIS', 'Wisdom')], default='HON', max_length=16),
        ),
    ]
