# Generated by Django 6.0.4 on 2026-04-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0183_alter_totem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='extra_freebies',
        ),
    ]
