# Generated by Django 6.0.4 on 2026-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0184_remove_creature_extra_freebies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='reparts',
            field=models.CharField(blank=True, default='7_5_3__13_9_5', max_length=32),
        ),
    ]
