# Generated by Django 6.0.4 on 2026-05-09 00:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0185_alter_creature_reparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sept',
            name='color',
            field=colorfield.fields.ColorField(default='#808080', image_field=None, max_length=25, samples=None),
        ),
    ]
