# Generated by Django 6.0.5 on 2026-05-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0186_sept_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='watch',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
