# Generated by Django 6.0.5 on 2026-05-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0187_adventure_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='watch',
            field=models.CharField(blank=True, default='Perception+Alertness', max_length=64),
        ),
    ]
