# Generated by Django 6.0.5 on 2026-05-10 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0188_alter_adventure_watch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_watch_criteria', models.CharField(blank=True, default='Dexterity+Brawl', max_length=100)),
                ('storyteller_for', models.CharField(blank=True, default='', max_length=256)),
                ('characters', models.CharField(blank=True, default='', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
