# Generated by Django 6.0.5 on 2026-05-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0189_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='characters',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='storyteller_for',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
