# Generated by Django 6.0.5 on 2026-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0190_alter_profile_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='quirks',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
