# Generated by Django 6.0.5 on 2026-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0191_creature_quirks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='kinfolk_gift',
            field=models.BooleanField(default=False),
        ),
    ]
