# Generated by Django 3.2.1 on 2021-06-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
