# Generated by Django 3.2.1 on 2021-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0002_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='exact_place',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
