# Generated by Django 3.2.1 on 2021-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0004_auto_20210718_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['time_offset_hours']},
        ),
        migrations.AddField(
            model_name='scene',
            name='objectives',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
