# Generated by Django 3.2.1 on 2021-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0005_auto_20210718_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='fallback',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
