# Generated by Django 3.2.1 on 2021-08-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0010_auto_20210729_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='timeline',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
