# Generated by Django 3.2.1 on 2021-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0012_alter_scene_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='preamble',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
