# Generated by Django 3.2.1 on 2021-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0013_alter_scene_preamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='consequences',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='scene',
            name='fallback',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='scene',
            name='objectives',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
