# Generated by Django 3.2.1 on 2021-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0015_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='side_treks',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
