# Generated by Django 3.2.1 on 2021-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0016_scene_side_treks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='special',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
