# Generated by Django 3.2.13 on 2022-05-05 15:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0022_city_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='color',
            field=colorfield.fields.ColorField(default='#808080', max_length=18),
        ),
        migrations.AddField(
            model_name='district',
            name='proeminent',
            field=models.CharField(default='', max_length=64),
        ),
    ]
