# Generated by Django 3.2.13 on 2022-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0023_auto_20220505_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
