# Generated by Django 3.2.13 on 2022-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0026_auto_20220505_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='proeminent',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
