# Generated by Django 3.2.13 on 2022-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0027_alter_district_proeminent'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
