# Generated by Django 3.2.13 on 2022-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0028_district_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='sector_name',
            field=models.CharField(default='', max_length=96),
        ),
    ]
