# Generated by Django 3.2.13 on 2022-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0029_district_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='d_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='district',
            name='s_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
