# Generated by Django 3.2.13 on 2022-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0032_auto_20220509_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.CharField(blank=True, default='neutral', max_length=64, null=True),
        ),
    ]
