# Generated by Django 3.2.13 on 2022-05-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0034_alter_district_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
