# Generated by Django 3.2.13 on 2022-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0035_district_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='camarilla_intelligence',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='camarilla_leisure',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='camarilla_power',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='camarilla_resources',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
