# Generated by Django 2.2.4 on 2023-05-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0039_auto_20220731_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
