# Generated by Django 2.2.4 on 2023-05-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0040_city_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='s_num',
        ),
    ]
