# Generated by Django 2.2.4 on 2023-05-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0042_auto_20230526_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_name',
            field=models.CharField(blank=True, default='', max_length=96, null=True),
        ),
    ]
