# Generated by Django 2.2.4 on 2023-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0043_district_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population_details',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
