# Generated by Django 4.2.1 on 2023-06-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0046_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storytelling.city'),
        ),
    ]
