# Generated by Django 4.2.1 on 2023-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0047_hotspot_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='gps_coords',
            field=models.CharField(blank=True, default='0,0', max_length=256),
        ),
    ]
