# Generated by Django 4.2.1 on 2023-06-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0050_alter_hotspot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'None'), ('ely', 'Camarilla Elysium'), ('hvn', 'Camarilla Haven'), ('ind', 'Indepentents PoI')], default='n/a', max_length=3),
        ),
    ]
