# Generated by Django 4.2.1 on 2023-06-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0051_alter_hotspot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
