# Generated by Django 4.2.1 on 2023-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0053_alter_hotspot_color_alter_hotspot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='hyperlink',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
