# Generated by Django 4.2.1 on 2023-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0058_alter_hotspot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='episode',
            field=models.CharField(default='', max_length=128),
        ),
    ]
