# Generated by Django 5.0 on 2024-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0063_city_chronicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='chronicle',
            field=models.CharField(default='WOD', max_length=8),
        ),
    ]
