# Generated by Django 5.1.12 on 2025-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0064_alter_city_chronicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='options',
            field=models.CharField(default='', max_length=128),
        ),
    ]
