# Generated by Django 5.0 on 2026-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0066_alter_city_description_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code_property',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='city',
            name='geojson_file',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='city',
            name='name_property',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='city',
            name='sector_property',
            field=models.CharField(default='', max_length=128),
        ),
    ]
