# Generated by Django 5.0 on 2026-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0068_city_lattitude_city_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
