# Generated by Django 5.0 on 2026-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0073_alter_city_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='chronicle',
            field=models.CharField(default='WOD', max_length=50),
        ),
    ]
