# Generated by Django 5.0 on 2026-02-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0074_alter_city_chronicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='options',
        ),
    ]
