# Generated by Django 5.0 on 2026-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0075_remove_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='font_scale',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
