# Generated by Django 5.0 on 2026-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0076_city_font_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='city_code',
            field=models.CharField(blank=True, default='UNY', max_length=128),
        ),
    ]
