# Generated by Django 5.0 on 2026-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0077_hotspot_city_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='type',
            field=models.CharField(blank=True, choices=[('n/a', 'None'), ('ely', 'Camarilla Elysium'), ('hvn', 'Camarilla Haven'), ('ind', 'Indepentents PoI'), ('hou', 'House of'), ('poi', 'Point Of Interest'), ('uba', 'U-bahn'), ('foe', 'Foes'), ('upo', 'Unexplored Point Of Interest'), ('mys', 'Mystery location'), ('gac', 'Garou Active Caern'), ('gdc', 'Garou Dormant Caern')], default='n/a', max_length=3),
        ),
    ]
