# Generated by Django 5.0 on 2026-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0078_alter_hotspot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
