# Generated by Django 5.0 on 2026-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0080_district_adventures'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='is_city',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
