# Generated by Django 5.0.14 on 2026-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0081_hotspot_is_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
