# Generated by Django 5.0.14 on 2026-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0083_alter_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
