# Generated by Django 6.0.4 on 2026-05-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0086_alter_scene_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='story',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='story',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
