# Generated by Django 6.0.4 on 2026-05-05 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0185_alter_creature_reparts'),
        ('storytelling', '0087_remove_place_story_remove_scene_story_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('acronym', models.CharField(default='', max_length=16)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('dday', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('chronicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.chronicle')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
