# Generated by Django 6.0.4 on 2026-05-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0089_scene_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storytelling.story'),
        ),
    ]
