# Generated by Django 6.0.4 on 2026-05-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0090_place_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='chronicle',
        ),
        migrations.AddField(
            model_name='story',
            name='adventure',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
