# Generated by Django 6.0.4 on 2026-05-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0091_remove_story_chronicle_story_adventure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='acronym',
        ),
    ]
