# Generated by Django 6.0.4 on 2026-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0092_remove_story_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='hours_duration',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
